### ISSUE TITLE
New release that includes extra header types

### ISSUE THREAD

**Issue by tmcgilchrist** [aristidb/http-types#58]
I'm working on a project that has defined some of it's own header types which are in master but not in 0.8.6 on hackage. When do you expect to be making a new release that'll include these new header definitions?

https://github.com/helium/airship/blob/master/src/Airship/Internal/Decision.hs#L47-L69

**Comment by josejuan** [comment]
Same here! :)

**Comment by aristidb** [comment]
0.9 is on Hackage! :)
