### ISSUE TITLE
What are the goals of URL handling in http-types?

### ISSUE THREAD

**Issue by seagreen** [aristidb/http-types#61]
Is the goal to provide some URL handling utilities (like extract the path from a bytestring, which http-types already provides) or to eventually provide comprehensive URL handling (e.g. extracting the scheme and fragment from a URL as well)?

Clarifying this would help users understand the difference between http-types and other libraries like uri-bytestring and network-uri.

**Comment by aristidb** [comment]
The goal is to provide only the parsing / generating methods for URIs
needed by a typical HTTP server or client. Non-HTTP URIs are out of scope.

Ian Jeffries <notifications@github.com> schrieb am So., 18. Okt. 2015 um
22:46 Uhr:

**Comment by seagreen** [comment]
Oh, that makes total sense. Thanks, and feel free to close this!
