### ISSUE TITLE
Importing Network.HTTP.Types un-imports Prelude

### ISSUE THREAD

**Issue by ksvanhorn** [aristidb/http-types#63]
In ghci, if I do :m + Network.HTTP.Types or import Network.HTTP.Types, I suddenly find that none of the Prelude identifiers are in scope any more -- not even True and False.

**Comment by aristidb** [comment]
That is weird, and I can't reproduce it. Which versions of ghc and http-types are you using?

**Comment by ksvanhorn** [comment]
Thanks for checking this out. I’m doing stack exec ghci, and it tells me the version is 7.10.3. According to stack exec ghc-pkg list, I have http-types-0.9.

**Comment by aristidb** [comment]
No module in http-types does anything with Prelude, so I'm not sure what
may be going on.

Can you work around it by doing "import Prelude"?

Kevin S. Van Horn <notifications@github.com> schrieb am Mo., 21. Dez. 2015
um 21:54 Uhr:

> Thanks for checking this out. I’m doing stack exec ghci, and it tells me
> the version is 7.10.3. According to stack exec ghc-pkg list, I have
> http-types-0.9.
>
> > On Dec 21, 2015, at 10:37 AM, Aristid Breitkreuz <

**Comment by ksvanhorn** [comment]
Yes, that works. Thank you. As someone new to the Haskell ecosystem, though, it was frustrating and puzzling to have this problem occur and not understand why.

**Comment by ksvanhorn** [comment]
On further investigation, I don't think is is a problem with http-types. It appears to be an issue with the cabal file in the directory in which I working.
