### ISSUE TITLE
What is the type of encodePathSegments?

### ISSUE THREAD

**Issue by mrkkrp** [aristidb/http-types#70]
OK, if you take a look at:

https://hackage.haskell.org/package/http-types-0.9.1/docs/Network-HTTP-Types-URI.html#v:encodePathSegments

The Haddock says that it returns `Builder` from `Data.Binary.Builder`, and indeed if I write code that interacts with `encodePathSegments` it seems true. While according to the source code you export the builder from `Blaze.ByteString.Builder` and older versions of Haddock also indicate that. I tried to blame on GitHub and I don't see when the change happened. `Data.Binary.Builder` and `Blaze.ByteString.Builder` do not seem to export each other's `Builder` type (in fact the packages do not depend on each other).

Any idea what is going on here?

**Comment by mrkkrp** [comment]
OK, it's still weird that it's linked to `Builder` from `binary` , but it looks like the both modules re-export builder from `bytestring`.

**Comment by aristidb** [comment]
blaze and binary got merged at some point, and all the blaze types are type aliases for the binary types now. http-types was kept as is so it would be compatible with both old and new versions of blaze. (Nowadays we could probably change it, I guess, but it also doesn't really hurt.)
