### ISSUE TITLE
Go back to uppercase URI encoding

### ISSUE THREAD

**Issue by DanBurton** [aristidb/http-types#83]
The [URI spec](https://tools.ietf.org/html/rfc3986#section-2.1) says:

> For consistency, URI producers and
   normalizers should use uppercase hexadecimal digits for all percent-
   encodings.

Given how widely used http-types is in the Haskell ecosystem, I think it would be wise to follow the spec's recommendation on this.

Additionally, please note that we may keep http-types constrained to 0.10 on Stackage, due to 0.11's adverse effect on amazonka request signing (see https://github.com/brendanhay/amazonka/issues/440) and other such packages.

See also: https://github.com/fpco/stackage/issues/3226

**Comment by aristidb** [comment]
Thanks for pointing this out, I was a little bit uneasy changing the case, but was at the time happy that using bytestring's hexadecimal function simplified the code.

If this breaks request signing of amazonka, I will definitely revert back to upper-case.

**Comment by aristidb** [comment]
@DanBurton Would you mind checking if the latest change would fix your issue? Also, is it good for you if I release this as 0.12 (it is technically a breaking change compared to 0.11...)?

**Comment by DanBurton** [comment]
> is it good for you if I release this as 0.12?

It will take some time for everyone to bump their upper bounds as usual, but that's fine by me.

> Would you mind checking if the latest change would fix your issue?

Sure, I'll give it a try and let you know how it goes.

**Comment by DanBurton** [comment]
I have tested the following:

* amazonka-ec2-1.5.0
* amazonka-s3-1.5.0
* amazonka-sqs-1.5.0

For each, I used the following stack.yaml

```yaml
resolver: nightly-2018-01-25
packages:
- .
extra-deps:
- git: git@github.com:aristidb/http-types
  commit: 86ef7fea760c767cb4a8c8bb917614be49a0306c
```

And ran

```bash
$ stack unpack $pkg
$ cd $pkg
$ vi stack.yaml # add the contents above
$ stack test
```

The test suite passed for each one. I have reasonable confidence that the latest change (commit 86ef7fea760c767cb4a8c8bb917614be49a0306c) did in fact fix this issue.

**Comment by aristidb** [comment]
0.12 is released.
