### ISSUE TITLE
Add the Generic typeclass to `StdMethod`

### ISSUE THREAD

**Issue by kahlil29** [aristidb/http-types#92]
Is there any reason why the `StdMethod` type does not have a `Generic` instance ? 
I need the `Generic` instance to derive another instance (Hashable) and was wondering if it would be possible to add it or if there's a specific reason why it's not present.

**Comment by aristidb** [comment]
Added. Please test whether current master works the way you needed.

**Comment by kahlil29** [comment]
@aristidb That was super quick! Thanks a bunch! I think that's exactly what I needed 😄
